-- Conspiracy Generator v2 — Postgres init script.
-- Runs once when the volume is empty. Subsequent schema changes happen via
-- explicit Drizzle migrations against the live db.
-- Spec: openspec/changes/v2-rebuild/specs/data-platform/spec.md

\set ON_ERROR_STOP on

-- Read the app role password from the file the entrypoint mounted.
\set app_password `cat /run/secrets/postgres_app_password`

-- Create the application database and a non-superuser role.
CREATE DATABASE cgen;

-- The :'app_password' bind protects against quoting issues; psql escapes it.
CREATE ROLE app WITH LOGIN PASSWORD :'app_password';

-- Ownership transfer + CREATE on the database so the app can run Drizzle
-- migrations (which create the `drizzle` schema for migration metadata).
ALTER DATABASE cgen OWNER TO app;
GRANT ALL ON DATABASE cgen TO app;

\connect cgen

-- App role owns everything inside the cgen database.
ALTER SCHEMA public OWNER TO app;
GRANT ALL ON SCHEMA public TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app;

-- Schema bootstrap (originally generated by drizzle-kit, kept in sync with web/drizzle/0000_init.sql).
SET ROLE app;

CREATE TYPE "public"."input_source" AS ENUM('curated', 'custom', 'migrated');
CREATE TYPE "public"."quiz_kind" AS ENUM('real', 'fake');
CREATE TYPE "public"."generation_source" AS ENUM('created', 'migrated');

CREATE TABLE IF NOT EXISTS "generations" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "short_id" text NOT NULL,
    "event_value" text NOT NULL,
    "event_source" "input_source" NOT NULL,
    "culprit_value" text NOT NULL,
    "culprit_source" "input_source" NOT NULL,
    "motive_value" text NOT NULL,
    "motive_source" "input_source" NOT NULL,
    "recipe_content" jsonb NOT NULL,
    "model_version" text NOT NULL,
    "recipe_version" text NOT NULL,
    "parent_generation_id" uuid,
    "created_at" timestamp with time zone,
    "source" "generation_source" DEFAULT 'created' NOT NULL,
    "session_hash" text
);

CREATE TABLE IF NOT EXISTS "quiz_items" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "kind" "quiz_kind" NOT NULL,
    "display_text" text NOT NULL,
    "source_generation_id" uuid,
    "historical_label" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "ratings" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "generation_id" uuid NOT NULL,
    "session_hash" text NOT NULL,
    "score" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "quiz_items"
    ADD CONSTRAINT "quiz_items_source_generation_id_generations_id_fk"
    FOREIGN KEY ("source_generation_id") REFERENCES "public"."generations"("id")
    ON DELETE set null ON UPDATE no action;

ALTER TABLE "ratings"
    ADD CONSTRAINT "ratings_generation_id_generations_id_fk"
    FOREIGN KEY ("generation_id") REFERENCES "public"."generations"("id")
    ON DELETE cascade ON UPDATE no action;

CREATE UNIQUE INDEX IF NOT EXISTS "generations_short_id_uq"  ON "generations" USING btree ("short_id");
CREATE INDEX        IF NOT EXISTS "generations_triple_idx"   ON "generations" USING btree ("event_value","culprit_value","motive_value");
CREATE INDEX        IF NOT EXISTS "generations_parent_idx"   ON "generations" USING btree ("parent_generation_id");
CREATE INDEX        IF NOT EXISTS "generations_created_at_idx" ON "generations" USING btree ("created_at");
CREATE INDEX        IF NOT EXISTS "quiz_items_kind_idx"      ON "quiz_items"   USING btree ("kind");
CREATE UNIQUE INDEX IF NOT EXISTS "ratings_one_per_session_uq" ON "ratings"     USING btree ("generation_id","session_hash");
CREATE INDEX        IF NOT EXISTS "ratings_generation_idx"   ON "ratings"     USING btree ("generation_id");

RESET ROLE;
