import streamlit as st

import datetime
import gspread
#from initialize_session_state import initialize_session_state_dict
import newspaper
from oauth2client.service_account import ServiceAccountCredentials
import os
import openai
import pandas as pd
import random
import requests
from streamlit_extras.badges import badge
import sys
import webbrowser

from ct_gen.src.modules.initialize_session_state import initalize_session_state_dict


# Initialize session state dictionary
def initialize_session_state():
    if 'official_version' not in st.session_state:
        st.session_state.official_version = ""
    if 'culprits' not in st.session_state:
        st.session_state.culprits = ""
    if 'goals' not in st.session_state:
        st.session_state.goals = ""
    if 'motive' not in st.session_state:
        st.session_state.motive = ""  
    if 'conspiracy_theory' not in st.session_state:
        st.session_state.conspiracy_theory = ""

def generate_conspiracy_theory():
    # Access the user inputs from the session state
    url = st.session_state.url
    culprits = st.session_state.culprits
    goals = st.session_state.goals
    motive_info = st.session_state.motive_info

    # Combine the user inputs to create the conspiracy theory
    conspiracy_theory = f"There is a conspiracy involving {culprits} aiming to {goals}. " \
                        f"They are operating against the official version which says: '{url}'. " \
                        f"The motive behind this conspiracy is to {motive_info}. " \
                        f"The truth is hidden and only the chosen ones can see it."

    # Save the generated conspiracy theory in the session state
    st.session_state.conspiracy_theory = conspiracy_theory


def display_page_6():
    
    st.markdown("### Page 6")
    st.warning('DISCLAIMER: DISCLAIMER: False conspiracy theories can be harmful. Please use our Conspiracy Generator with caution and do not target vulnerable groups of individuals.', icon="⚠️")
    st.title("🔦 Your conspiracy theory")
    st.markdown("Here is you conspiracy theory generated by Chatgpt:") 

    # Call the function to generate the conspiracy theory
    st.subheader("Generated Conspiracy Theory")
    generate_conspiracy_theory()

    # Display the generated conspiracy theory
    st.write(st.session_state.conspiracy_theory)