// /quiz — five-question real-or-fake quiz.
// Spec: openspec/changes/v2-rebuild/specs/quiz-mode/spec.md
//
// Real items: Watergate / COINTELPRO / Iran-Contra / Tuskegee / MK-ULTRA (locked at build).
// Fake items: drawn from the v2 generations table (or v1 migrated rows in legacy_text shape).
// 3-4 fakes + 1-2 reals, randomized.

import Link from "next/link";
import { sql } from "drizzle-orm";
import { db, schema } from "@/lib/db";
import { Masthead } from "@/components/masthead";
import { Footer } from "@/components/footer";
import { QuizGame } from "@/components/quiz-game";
import realData from "@/data/real-conspiracies.json";

export const metadata = { title: "Real or fake?" };
export const dynamic = "force-dynamic";

type QuizItem = {
  id: string;
  kind: "real" | "fake";
  text: string;
  label?: string;
};

async function buildQuiz(): Promise<QuizItem[]> {
  // 1-2 reals, 3-4 fakes
  const realCount = Math.random() < 0.5 ? 1 : 2;
  const fakeCount = 5 - realCount;

  const realPool = [...realData].sort(() => Math.random() - 0.5).slice(0, realCount);
  const reals: QuizItem[] = realPool.map((r, i) => ({
    id: `real-${i}-${r.label}`,
    kind: "real",
    text: r.summary,
    label: r.label,
  }));

  // Pull random fake summaries from the database. Use only rows that have the
  // recipe-tagged shape (not legacy_text dumps); condense by joining the four
  // moves and trimming to ~600 chars.
  let fakes: QuizItem[] = [];
  try {
    const rows = await db()
      .select({
        shortId: schema.generations.shortId,
        recipeContent: schema.generations.recipeContent,
        culpritValue: schema.generations.culpritValue,
        eventValue: schema.generations.eventValue,
      })
      .from(schema.generations)
      .where(sql`${schema.generations.recipeContent} ? 'anomalies'`)
      .orderBy(sql`random()`)
      .limit(fakeCount);

    fakes = rows.map((r) => {
      const c = r.recipeContent as { anomalies?: string; connect_dots?: string; dismiss_counter?: string; discredit_critics?: string };
      const flat = [c.anomalies, c.connect_dots, c.dismiss_counter, c.discredit_critics]
        .filter(Boolean)
        .join(" ")
        .replace(/\s+/g, " ")
        .trim();
      return {
        id: `fake-${r.shortId}`,
        kind: "fake",
        text: flat.slice(0, 600) + (flat.length > 600 ? "…" : ""),
      };
    });
  } catch (err) {
    console.warn("[quiz] db unavailable, using only real items:", err);
  }

  // If we have fewer fakes than expected (empty DB locally), top up reals so
  // the quiz still has 5 items and is honest about the mix.
  while (reals.length + fakes.length < 5 && reals.length < realData.length) {
    const remaining = realData.find((r) => !reals.some((rr) => rr.label === r.label));
    if (!remaining) break;
    reals.push({
      id: `real-extra-${remaining.label}`,
      kind: "real",
      text: remaining.summary,
      label: remaining.label,
    });
  }

  const all = [...reals, ...fakes].sort(() => Math.random() - 0.5);
  return all;
}

export default async function QuizPage() {
  const items = await buildQuiz();
  return (
    <>
      <Masthead />

      <article className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-14 lg:py-16">
        <p className="meta">Quiz</p>
        <h1
          className="mt-3 font-display text-[clamp(2rem,5vw,3.25rem)] leading-[1.05]"
          style={{ fontWeight: 600, letterSpacing: "-0.025em" }}
        >
          Real conspiracy or fake?
        </h1>
        <p className="mt-5 text-[16px] leading-relaxed text-ink-soft dark:text-ink-soft-dark">
          Five short summaries. Some are real historical conspiracies — documented by paper trails,
          defectors, and prosecutions. Others are fakes generated by this app. Can you tell which is
          which?
        </p>
        <QuizGame items={items} />
        <p className="mt-10 text-[13px] italic text-ink-soft dark:text-ink-soft-dark">
          The "real" pool is conservative on purpose: only conspiracies with broad documentary consensus
          across mainstream sources appear. Contested historical or contemporary events do not.
        </p>
        <div className="mt-6">
          <Link href="/recipe" className="underline-offset-2 hover:underline text-[14px]">
            Read the recipe →
          </Link>
        </div>
      </article>

      <Footer />
    </>
  );
}
